[project]
name = "supervaize-hello-world"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastapi>=0.128.0", "loguru>=0.7.3", "supervaizer>=0.10.20"]
